MapaActividades = {
    0: "En vehículo",
    1: "Ciclismo",
    3: "Quieto",
    4: "Desconocido",
    5: "Inclinación brusca del dispositivo por cambio de gravedad",
    7: "Caminata",
    8: "Correr",
    9: "Aeróbicos",
    10: "Bádminton",
    11: "Béisbol",
    12: "Baloncesto",
    13: "Biatlón",
    14: "Ciclismo de mano",
    15: "Ciclismo de montaña",
    16: "Ciclismo de carretera",
    17: "Spinning",
    18: "Ciclismo estático",
    19: "Ciclismo utilitario",
    20: "Boxeo",
    21: "Calistenia",
    22: "Entrenamiento en circuito",
    23: "Críquet",
    24: "Baile",
    25: "Elíptica",
    26: "Esgrima",
    27: "Fútbol americano",
    28: "Fútbol australiano",
    29: "Fútbol",
    30: "Frisbee",
    31: "Jardinería",
    32: "Golf",
    33: "Gimnasia",
    34: "Balonmano",
    35: "Senderismo",
    36: "Hockey",
    37: "Equitación",
    38: "Tareas domésticas",
    39: "Saltar la cuerda",
    40: "Kayak",
    41: "Entrenamiento con pesas rusas",
    42: "Kickboxing",
    43: "Kitesurf",
    44: "Artes marciales",
    45: "Meditación",
    46: "Artes marciales mixtas",
    47: "Ejercicios P90X",
    48: "Parapente",
    49: "Pilates",
    50: "Polo",
    51: "Racquetball",
    52: "Escalada en roca",
    53: "Remo",
    54: "Remo en máquina",
    55: "Rugby",
    56: "Trote",
    57: "Correr en arena",
    58: "Correr en cinta",
    59: "Vela",
    60: "Buceo",
    61: "Skateboarding",
    62: "Patinar",
    63: "Patinaje cruzado",
    64: "Patinaje en línea",
    65: "Esquí",
    66: "Esquí de travesía",
    67: "Esquí de fondo",
    68: "Esquí alpino",
    69: "Esquí con cometa",
    70: "Esquí de ruedas",
    71: "Trineo",
    73: "Snowboard",
    74: "Motonieve",
    75: "Raquetas de nieve",
    76: "Squash",
    77: "Escalada de escaleras",
    78: "Máquina escaladora",
    79: "Paddle surf",
    80: "Entrenamiento de fuerza",
    81: "Surf",
    82: "Natación",
    84: "Natación en aguas abiertas",
    83: "Natación en piscina",
    85: "Tenis de mesa",
    86: "Deportes de equipo",
    87: "Tenis",
    88: "Caminadora",
    89: "Voleibol",
    90: "Voleibol de playa",
    91: "Voleibol de interior",
    92: "Wakeboard",
    93: "Caminata fitness",
    94: "Marcha nórdica",
    95: "Caminata en caminadora",
    96: "Polo acuático",
    97: "Levantamiento de pesas",
    98: "Silla de ruedas",
    99: "Windsurf",
    100: "Yoga",
    101: "Zumba",
    102: "Buceo",
    103: "Ergómetro",
    104: "Patinaje sobre hielo",
    105: "Patinaje en interiores",
    106: "Curling",
    108: "Otro",
    113: "Crossfit",
    114: "HIIT",
    115: "Entrenamiento por intervalos",
    116: "Caminata con cochecito",
    117: "Ascensor",
    118: "Escalera mecánica",
    119: "Tiro con arco",
    120: "Softball",
    122: "Respiración guiada",
}

MapSleepType = {
    0: "No especificado",
    1: "Despierto",
    2: "Durmiendo",
    3: "Fuera de la cama",
    4: "Sueño ligero",
    5: "Sueño profundo",
    6: "Sueño REM",
}
